### ISSUE TITLE
Discretization

### ISSUE THREAD

**Issue by craftograf** [csillagu/FVM-Solver#7]
Creates the matrixes for the solver

**Comment by csillagu** [comment]
The discretization class should have the following connections to other classes.

Inputs:
 - A subclass of the Mesh class, where the following information is stored: list of elements, index of the neighbouring elements, (relative) position of the neighbouring elements, neighbouring faces for each element, length of said faces, normal vectors of the faces, volume of the element
 - Physics class: Information on boundaries (is an element one, type, needed constants of the boundary conditions), flux value calculation scheme of different elements with the following syntax: `Physics.getFluxValue(volume, face_normal, face_length, neighbour_position)` and returns the (self and neighbour) coefficients and the constant as described here: ![image](https://github.com/csillagu/FVM-Solver/assets/71261575/f3496936-f0a9-49d6-be99-0de62c044ab7)
 - Parametrization of the problem (this will be used later for solving nonlinear systems)

Outputs:

 - Full A and b matrices

The class should also be able to convert the matemathical coordinates back to physical ones
